# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2268244eea75426561f5697d862cea8da25c67a8f236d0ac0c3cf6da852566fa9fb95556dc3c2c227c62d4435c6c049a88fa93856b9a7eaa89c43087a37958ec

test:
  secret_key_base: fc28f585654b655517b078e2e854645837fec8058d00c7326b10aa93c4d90863189b64c990f50314d263090f72e2474b9ad228452fb172f3940c5d1e06ab1577

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
